name: bell_challenge_game
description: "A bell challenge game ported from React Native to Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  vibration: ^3.1.4
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1
  uuid: ^4.2.1
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/audio/bgm/
    - assets/audio/se/
    - assets/images/
    - lib/i18n/

  # iOS Configuration
  generate: true
